#ifndef RANDOM_SAMPLE_GENERATOR_H
#define RANDOM_SAMPLE_GENERATOR_H

#include <vector>

#include "Sample.h"

/*
Description:

   The SampleGenerator class is used to generate Sample objects for every pixel on the image plane.

   Each sample specifies the coordinates of the center of a pixel.

   The samples generated by this class are used to compute the rays that are shot by the camera through the center of each pixel.
*/

class RandomSampleGenerator
{
public:

   RandomSampleGenerator();
   RandomSampleGenerator(const int width, const int height);
   ~RandomSampleGenerator();

   void generateSample(Sample& sample);

   bool sampleIsAvailable();

   float getProgress();

private:

   // Number of pixels = Number of samples = width * height
   unsigned int width, height;

   std::vector<std::pair<int, int>> coordinates;
   std::vector<std::pair<int, int>>::iterator currentCoordinate;

   unsigned int numSamplesGenerated;
};

#endif

